spring:
    application:
        name: devoxbe
    security:
        oauth2:
            client:
                registration:
                    facebook:
                        client-id: hgjjh
                        client-secret: tg6tgfty
